# Generated by Django 5.2.6 on 2025-10-18 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_registration'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='uploads/'),
        ),
    ]
